
project_id = "pewmzdrzvjopdvngynhy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = ""

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template = {}

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[edge_runtime]
enabled = true
port = 54328

[analytics]
enabled = false
port = 54327
vector_port = 54329
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

[functions.gumroad-webhook]
verify_jwt = false

[functions.analyze-contract]
verify_jwt = true

[functions.legal-widgets]
verify_jwt = true

[functions.redeem-promo-code]
verify_jwt = true
